version: 1.0.0-{branch}-{build}
skip_branch_with_pr: true

environment:
  ASSEMBLY_FILE_VERSION: 1.0.0

configuration: Release
platform: Any CPU

before_build:
  - nuget restore
  - nuget install AppVeyorAssemblyVersionInfoWriter -Version 1.0.0 -OutputDirectory packages
  - packages\AppVeyorAssemblyVersionInfoWriter.1.0.0\tools\AppVeyorAssemblyVersionInfoWriter.exe --output VersionInfo.cs

build:
  include_nuget_references: true
  publish_nuget: true
  publish_nuget_symbols: false
